let formu=document.querySelector('#formu')
let puntos=document.querySelector('#puntos')
let contenedor=document.querySelector('#contenedorPrincipal')
let btnList=document.getElementById('listBtn')
let tabla=document.querySelector('#tabla')
let cont=document.querySelector('#cont')
let modalchild=document.querySelector('#modalchild')
let closemodal=document.querySelector('#closemodal')
let modal=document.querySelector('#modal')
let contenedorUpdate=document.querySelector('#contenedorUpdate')
let formUpdate=document.querySelector('#formUpdate')
let contenedorUpdatePuntos=document.querySelector('#contenedorUpdatePuntos')
let formUpdatePuntos=document.querySelector('#formUpdatePuntos')
let contenedorUpdateAgregar=document.querySelector('#contenedorUpdateAgregar')
let formUpdateAgregar=document.querySelector('#formUpdateAgregar')
export {formu, puntos, contenedor, btnList, tabla, cont, modalchild, closemodal, modal, contenedorUpdate, formUpdate, contenedorUpdatePuntos, formUpdatePuntos, contenedorUpdateAgregar, formUpdateAgregar}